travis:
  secure:
    BINSTAR_TOKEN: uB7i6F/2EHtYtKmY2JVvSGbBYYYTDZhQks51HDKhMEXgKgeA5wjGtGpfl1FW0OIa77hxY5IBLvvpAf5PNJZG5kMFdxL6jmQnxkpoWHycbO54kZMKHXCPKVfaobUDDui6iZ1f6bSWeswabgdevgpGBNX9sOvMOq81UZvAcbpx7f+D7bG0pFSmiibM0HruwkCuZVsv/P71gge3JY1JA2s+RMbXo67LfZTGsxmI+SNEXUSRxK4Xm9pE67qOMpBvBr7TrNzXceJHeUZK41QtGeVV34fE9hdka6epu8TkVyrr4k2Z/7M+ZHwL2OV8AOqHxman03dtZdkgoBoIDZv6tW8m3SDyOwTim+/Mo6Cc94SBLyDEId10x5RM0BBt0CiuRxzk3ylQhSBY+ooP4NvbQ7pIis1swH6O7sYqf3lhWV0vq16f8Th95HCliJHznx4MqPUs19KTVJ0F6BvEQIz6LKdA5UyFiQx45DmJO4xfd+HbSmRxqrK8G7s9jZpGPAPcc2b7uw6BcGReJISYSKxYz9sCagfuaEioYWTQB9PvrituXzlWgv5hSRAQjbkR4t81ft8yvLQ/ry18MmB0sYBARqMc4lfGXtuINEVSLmiARcEL4e30cOEKVkiwBSCFHj53WEPrkTlm2P99K+QLpdTFkV0qNHrKvBQ0JiJPET5JpcDFFXw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
