travis:
  secure:
    BINSTAR_TOKEN: cAqLTtgWHt5gB1BXV1srjrZ5yhgMBqOfTrU4Suy8vPkaL+1KB8dbHsOJMCqmqZAS2QTBQn+Tek0s0D1LcT7noci4YAMm2JJqPf9/vcyFgS0anNDkAaJ98thxYYYmFFostWUY4LtTNoYzNHZMY580IwxzHwuCanDfhZXsiPXdUpMBLZde/8nZ/yXTkbe2FB2QJ6fVmxtgdUjQFebjgKiDBhM74Xhg5KyQUaf4opKgSDF5st72F7MkobHOJG4ZOHfdjm8F2qhFqAtDeU7LYuZLsgORTpw6/E334BDrnrXBiTaaUNU/eUGWNoz+ZPhFZE1m6qlxqf6LgOeFUdzzNLdsDWP2G2Ppt4Wb4ccVbF86bQNShVCPjyEPGUxaERrzcU2GgqAoeprZD73WjR2nU/tc4vkk2unNgDbKdB8jxGLOx02RitdbzsaIb/cMaCoay53OciietCkenqrvuQPVhUPbj+msSfQmN09nwy0/dpidyS55S7S+K2eGRz0+XrrC8+u0GMS2F9CygMGHXc1bFb3+tXeM/LDGWGS8Riuj6qbnxWJUZUGbYzAGmRhAhvhnIWMhl5sXFDHqDhuZPT9U4gJz0N1TFKFRwwH5NGwWwB7z1WTdm/UGYkG5PyjXgkWMMTpR2EEFcK7d2cwCDExyGs+S1jEqdY5G7CUS1TryTLK1xbo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
